### ISSUE TITLE
keystoneauth1.exceptions.http.InternalServerError

### ISSUE THREAD

**Issue by shurdanil** [cloudbase/python-coriolisclient#76]
coriolis --debug endpoint list
WARNING: Unable to determine logging endpoint: no logging endpoint found in service catalogue
ERROR: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-18b6580a-f73b-4fa9-a3c6-4f07b8211534)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cliff/app.py", line 410, in run_subcommand
    result = cmd.run(parsed_args)
  File "/usr/lib/python3/dist-packages/cliff/display.py", line 117, in run
    column_names, data = self.take_action(parsed_args)
  File "/usr/local/lib/python3.10/dist-packages/coriolisclient/cli/endpoints.py", line 249, in take_action
    obj_list = self.app.client_manager.coriolis.endpoints.list()
  File "/usr/local/lib/python3.10/dist-packages/coriolisclient/v1/endpoints.py", line 39, in list
    return self._list('/endpoints', 'endpoints')
  File "/usr/local/lib/python3.10/dist-packages/coriolisclient/base.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/coriolisclient/base.py", line 182, in _list
    body = self.client.get(url).json()
  File "/usr/lib/python3/dist-packages/keystoneauth1/adapter.py", line 395, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python3/dist-packages/keystoneauth1/adapter.py", line 257, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python3/dist-packages/keystoneauth1/session.py", line 986, in request
    raise exceptions.from_response(resp, method, url)
keystoneauth1.exceptions.http.InternalServerError: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-18b6580a-f73b-4fa9-a3c6-4f07b8211534)

Cannot work with coriolis, because get this error. Made installation by https://github.com/cloudbase/coriolis-resources/blob/master/install_coriolis.sh

**Comment by shurdanil** [comment]
Maybe it's because of

024-01-24 11:18:09.558 3351 CRITICAL coriolis [-] Unhandled error: oslo_db.exception.DBMigrationError: (pymysql.err.OperationalError) (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
[SQL:
CREATE TABLE endpoint_region_mapping (
        id VARCHAR(36) NOT NULL,
        endpoint_id VARCHAR(36) NOT NULL,
        region_id VARCHAR(36) NOT NULL,
        created_at DATETIME,
        updated_at DATETIME,
        deleted_at DATETIME,
        deleted VARCHAR(36),
        PRIMARY KEY (id),
        FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
        FOREIGN KEY(region_id) REFERENCES region (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-24 11:18:09.558 3351 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
2024-01-24 11:18:09.558 3351 ERROR coriolis     self.dialect.do_execute(
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
2024-01-24 11:18:09.558 3351 ERROR coriolis     cursor.execute(statement, parameters)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 148, in execute
2024-01-24 11:18:09.558 3351 ERROR coriolis     result = self._query(query)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 310, in _query
2024-01-24 11:18:09.558 3351 ERROR coriolis     conn.query(q)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 548, in query
2024-01-24 11:18:09.558 3351 ERROR coriolis     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 775, in _read_query_result
2024-01-24 11:18:09.558 3351 ERROR coriolis     result.read()
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1156, in read
2024-01-24 11:18:09.558 3351 ERROR coriolis     first_packet = self.connection._read_packet()
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 725, in _read_packet
2024-01-24 11:18:09.558 3351 ERROR coriolis     packet.raise_for_error()
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-24 11:18:09.558 3351 ERROR coriolis     err.raise_mysql_exception(self._data)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-24 11:18:09.558 3351 ERROR coriolis     raise errorclass(errno, errval)
2024-01-24 11:18:09.558 3351 ERROR coriolis pymysql.err.OperationalError: (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis The above exception was the direct cause of the following exception:
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/oslo_db/sqlalchemy/migration.py", line 87, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis     migration = versioning_api.upgrade(engine, repository, version)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/api.py", line 186, in upgrade
2024-01-24 11:18:09.558 3351 ERROR coriolis     return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "<decorator-gen-15>", line 2, in _migrate
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
2024-01-24 11:18:09.558 3351 ERROR coriolis     return f(*a, **kw)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/api.py", line 366, in _migrate
2024-01-24 11:18:09.558 3351 ERROR coriolis     schema.runchange(ver, change, changeset.step)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/schema.py", line 93, in runchange
2024-01-24 11:18:09.558 3351 ERROR coriolis     change.run(self.engine, step)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/script/py.py", line 154, in run
2024-01-24 11:18:09.558 3351 ERROR coriolis     script_func(engine)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/local/lib/python3.10/dist-packages/coriolis/db/sqlalchemy/migrate_repo/versions/014_adds_worker_service_regions.py", line 119, in upgrade
2024-01-24 11:18:09.558 3351 ERROR coriolis     table.create()
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 950, in create
2024-01-24 11:18:09.558 3351 ERROR coriolis     bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
2024-01-24 11:18:09.558 3351 ERROR coriolis     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
2024-01-24 11:18:09.558 3351 ERROR coriolis     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
2024-01-24 11:18:09.558 3351 ERROR coriolis     return meth(obj, **kw)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
2024-01-24 11:18:09.558 3351 ERROR coriolis     self.connection.execute(
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1289, in execute
2024-01-24 11:18:09.558 3351 ERROR coriolis     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
2024-01-24 11:18:09.558 3351 ERROR coriolis     return connection._execute_ddl(
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
2024-01-24 11:18:09.558 3351 ERROR coriolis     ret = self._execute_context(
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
2024-01-24 11:18:09.558 3351 ERROR coriolis     self._handle_dbapi_exception(
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2024, in _handle_dbapi_exception
2024-01-24 11:18:09.558 3351 ERROR coriolis     util.raise_(newraise, with_traceback=exc_info[2], from_=e)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
2024-01-24 11:18:09.558 3351 ERROR coriolis     raise exception
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
2024-01-24 11:18:09.558 3351 ERROR coriolis     self.dialect.do_execute(
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
2024-01-24 11:18:09.558 3351 ERROR coriolis     cursor.execute(statement, parameters)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 148, in execute
2024-01-24 11:18:09.558 3351 ERROR coriolis     result = self._query(query)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 310, in _query
2024-01-24 11:18:09.558 3351 ERROR coriolis     conn.query(q)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 548, in query
2024-01-24 11:18:09.558 3351 ERROR coriolis     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 775, in _read_query_result
2024-01-24 11:18:09.558 3351 ERROR coriolis     result.read()
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1156, in read
2024-01-24 11:18:09.558 3351 ERROR coriolis     first_packet = self.connection._read_packet()
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 725, in _read_packet
2024-01-24 11:18:09.558 3351 ERROR coriolis     packet.raise_for_error()
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-24 11:18:09.558 3351 ERROR coriolis     err.raise_mysql_exception(self._data)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-24 11:18:09.558 3351 ERROR coriolis     raise errorclass(errno, errval)
2024-01-24 11:18:09.558 3351 ERROR coriolis sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
2024-01-24 11:18:09.558 3351 ERROR coriolis [SQL:
2024-01-24 11:18:09.558 3351 ERROR coriolis CREATE TABLE endpoint_region_mapping (
2024-01-24 11:18:09.558 3351 ERROR coriolis     id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis     endpoint_id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis     region_id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis     created_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis     updated_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis     deleted_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis     deleted VARCHAR(36),
2024-01-24 11:18:09.558 3351 ERROR coriolis     PRIMARY KEY (id),
2024-01-24 11:18:09.558 3351 ERROR coriolis     FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
2024-01-24 11:18:09.558 3351 ERROR coriolis     FOREIGN KEY(region_id) REFERENCES region (id)
2024-01-24 11:18:09.558 3351 ERROR coriolis )
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis ]
2024-01-24 11:18:09.558 3351 ERROR coriolis (Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis During handling of the above exception, another exception occurred:
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/root/coriolis-resources/coriolis/coriolis/cmd/db_sync.py", line 23, in <module>
2024-01-24 11:18:09.558 3351 ERROR coriolis     main()
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/root/coriolis-resources/coriolis/coriolis/cmd/db_sync.py", line 19, in main
2024-01-24 11:18:09.558 3351 ERROR coriolis     db_api.db_sync(db_api.get_engine())
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/local/lib/python3.10/dist-packages/coriolis/db/api.py", line 41, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis     return IMPL.db_sync(engine, version=version)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/local/lib/python3.10/dist-packages/coriolis/db/sqlalchemy/api.py", line 46, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis     return migration.db_sync(engine, version=version)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/local/lib/python3.10/dist-packages/coriolis/db/sqlalchemy/migration.py", line 14, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis     return oslo_migration.db_sync(engine, path, version,
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/debtcollector/removals.py", line 242, in wrapper
2024-01-24 11:18:09.558 3351 ERROR coriolis     return f(*args, **kwargs)
2024-01-24 11:18:09.558 3351 ERROR coriolis   File "/usr/lib/python3/dist-packages/oslo_db/sqlalchemy/migration.py", line 89, in db_sync
2024-01-24 11:18:09.558 3351 ERROR coriolis     raise exception.DBMigrationError(ex)
2024-01-24 11:18:09.558 3351 ERROR coriolis oslo_db.exception.DBMigrationError: (pymysql.err.OperationalError) (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
2024-01-24 11:18:09.558 3351 ERROR coriolis [SQL:
2024-01-24 11:18:09.558 3351 ERROR coriolis CREATE TABLE endpoint_region_mapping (
2024-01-24 11:18:09.558 3351 ERROR coriolis     id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis     endpoint_id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis     region_id VARCHAR(36) NOT NULL,
2024-01-24 11:18:09.558 3351 ERROR coriolis     created_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis     updated_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis     deleted_at DATETIME,
2024-01-24 11:18:09.558 3351 ERROR coriolis     deleted VARCHAR(36),
2024-01-24 11:18:09.558 3351 ERROR coriolis     PRIMARY KEY (id),
2024-01-24 11:18:09.558 3351 ERROR coriolis     FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
2024-01-24 11:18:09.558 3351 ERROR coriolis     FOREIGN KEY(region_id) REFERENCES region (id)
2024-01-24 11:18:09.558 3351 ERROR coriolis )
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:18:09.558 3351 ERROR coriolis ]
2024-01-24 11:18:09.558 3351 ERROR coriolis (Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-24 11:18:09.558 3351 ERROR coriolis
2024-01-24 11:36:11.509 2772 INFO migrate.versioning.api [-] 13 -> 14...
2024-01-24 11:36:11.572 2772 CRITICAL coriolis [-] Unhandled error: oslo_db.exception.DBMigrationError: (pymysql.err.OperationalError) (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
[SQL:
CREATE TABLE endpoint_region_mapping (
        id VARCHAR(36) NOT NULL,
        endpoint_id VARCHAR(36) NOT NULL,
        region_id VARCHAR(36) NOT NULL,
        created_at DATETIME,
        updated_at DATETIME,
        deleted_at DATETIME,
        deleted VARCHAR(36),
        PRIMARY KEY (id),
        FOREIGN KEY(endpoint_id) REFERENCES endpoint (id),
        FOREIGN KEY(region_id) REFERENCES region (id)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2024-01-24 11:36:11.572 2772 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
2024-01-24 11:36:11.572 2772 ERROR coriolis     self.dialect.do_execute(
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 732, in do_execute
2024-01-24 11:36:11.572 2772 ERROR coriolis     cursor.execute(statement, parameters)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 148, in execute
2024-01-24 11:36:11.572 2772 ERROR coriolis     result = self._query(query)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/cursors.py", line 310, in _query
2024-01-24 11:36:11.572 2772 ERROR coriolis     conn.query(q)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 548, in query
2024-01-24 11:36:11.572 2772 ERROR coriolis     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 775, in _read_query_result
2024-01-24 11:36:11.572 2772 ERROR coriolis     result.read()
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 1156, in read
2024-01-24 11:36:11.572 2772 ERROR coriolis     first_packet = self.connection._read_packet()
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 725, in _read_packet
2024-01-24 11:36:11.572 2772 ERROR coriolis     packet.raise_for_error()
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/protocol.py", line 221, in raise_for_error
2024-01-24 11:36:11.572 2772 ERROR coriolis     err.raise_mysql_exception(self._data)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/pymysql/err.py", line 143, in raise_mysql_exception
2024-01-24 11:36:11.572 2772 ERROR coriolis     raise errorclass(errno, errval)
2024-01-24 11:36:11.572 2772 ERROR coriolis pymysql.err.OperationalError: (3780, "Referencing column 'endpoint_id' and referenced column 'id' in foreign key constraint 'endpoint_region_mapping_ibfk_1' are incompatible.")
2024-01-24 11:36:11.572 2772 ERROR coriolis
2024-01-24 11:36:11.572 2772 ERROR coriolis The above exception was the direct cause of the following exception:
2024-01-24 11:36:11.572 2772 ERROR coriolis
2024-01-24 11:36:11.572 2772 ERROR coriolis Traceback (most recent call last):
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/oslo_db/sqlalchemy/migration.py", line 87, in db_sync
2024-01-24 11:36:11.572 2772 ERROR coriolis     migration = versioning_api.upgrade(engine, repository, version)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/api.py", line 186, in upgrade
2024-01-24 11:36:11.572 2772 ERROR coriolis     return _migrate(url, repository, version, upgrade=True, err=err, **opts)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "<decorator-gen-15>", line 2, in _migrate
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
2024-01-24 11:36:11.572 2772 ERROR coriolis     return f(*a, **kw)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/api.py", line 366, in _migrate
2024-01-24 11:36:11.572 2772 ERROR coriolis     schema.runchange(ver, change, changeset.step)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/schema.py", line 93, in runchange
2024-01-24 11:36:11.572 2772 ERROR coriolis     change.run(self.engine, step)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/migrate/versioning/script/py.py", line 154, in run
2024-01-24 11:36:11.572 2772 ERROR coriolis     script_func(engine)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/local/lib/python3.10/dist-packages/coriolis/db/sqlalchemy/migrate_repo/versions/014_adds_worker_service_regions.py", line 119, in upgrade
2024-01-24 11:36:11.572 2772 ERROR coriolis     table.create()
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 950, in create
2024-01-24 11:36:11.572 2772 ERROR coriolis     bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 3117, in _run_ddl_visitor
2024-01-24 11:36:11.572 2772 ERROR coriolis     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2113, in _run_ddl_visitor
2024-01-24 11:36:11.572 2772 ERROR coriolis     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
2024-01-24 11:36:11.572 2772 ERROR coriolis     return meth(obj, **kw)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 893, in visit_table
2024-01-24 11:36:11.572 2772 ERROR coriolis     self.connection.execute(
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1289, in execute
2024-01-24 11:36:11.572 2772 ERROR coriolis     return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
2024-01-24 11:36:11.572 2772 ERROR coriolis     return connection._execute_ddl(
2024-01-24 11:36:11.572 2772 ERROR coriolis   File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1381, in _execute_ddl
2024-01-24 11:36:11.572 2772 ERROR coriolis     ret = self._execute_context(

**Comment by aznashwan** [comment]
Hello @shurdanil, and thank you for your interest in Coriolis!

> Made installation by https://github.com/cloudbase/coriolis-resources/blob/master/install_coriolis.sh

Coriolis has evolved a lot since that initial quick setup script was written, and we have long switched to a deployment approach using OpenStack Kolla (Ansible-managed Docker containers), so please consider that installation script as deprecated.

Because of Coriolis' microservice-based architecture, deploying and managing Coriolis manually by yourself is way more error-prone than ideal, and the current recommended deployment method for Coriolis is via a self-contained virtualized appliance image we offer to customers directly.

Please reach out to us via the [contact form on Coriolis' page on our website](https://cloudbase.it/coriolis/) so we can hook you up with a trial appliance through that channel.
